const data = [
  "Motivational",
  "Energetic",
  "Encouraging",
  "Passionate",
  "Supportive",
  "Patient",
  "Compassionate",
  "Cheerful",
  "Empowering",
  "Inspiring",
  "Organized",
  "Detail-Oriented",
  "Systematic",
  "Disciplined",
  "Efficient",
  "Pragmatic",
  "Objective",
  "Methodical",
  "Goal-Oriented",
  "Thorough",
  "Flexible",
  "Intuitive",
  "Observant",
  "Empirical",
  "Reflective",
  "Adaptive",
  "Innovative",
  "Spontaneous",
  "Experimental",
  "Resourceful",
  "Scholarly",
  "Analytical",
  "Insightful",
  "Philosophical",
  "Curious",
  "Articulate",
  "Conceptual",
  "Logical",
  "Research-Oriented",
  "Practical",
  "Entertaining",
  "Creative",
  "Charismatic",
  "Storyteller",
  "Playful",
  "Expressive",
  "Dynamic",
  "Sociable",
  "Warm",
  "Relaxed",
];

export const teachingStyles = [];
data.forEach((style) => {
  teachingStyles.push({ value: style, label: style });
});
